apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
data:
  master.conf: |
   bind 0.0.0.0
  sentinel.conf: |
   # 哨兵配置
   port 26379
   sentinel monitor mymaster redis-0.redis-svc 6379 2
   sentinel down-after-milliseconds mymaster 60000
   sentinel failover-timeout mymaster 180000
   sentinel parallel-syncs mymaster 1 
