apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-cfg
  labels:
    app: redis-sentinel-cfg
data:
  sentinel.conf: |
   # 哨兵配置
   port 26379
   sentinel monitor mymaster redis-master-svc.default.svc.cluster.local 6379 2
   sentinel down-after-milliseconds mymaster 60000
   sentinel failover-timeout mymaster 180000
   sentinel parallel-syncs mymaster 1
   protected-mode no
   sentinel deny-scripts-reconfig yes
   SENTINEL resolve-hostnames yes
   SENTINEL announce-hostnames no
   dir /tmp
