apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: redis:7.0.11
        command: ["redis-server","/etc/redis/redis.conf"]
        ports:
        - containerPort:  6379
          name:  redis
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
      volumes:
        - name: redis-config
          configMap:
            name: redis-slave-cfg
            items:
            - key: "slave.conf"
              path: "redis.conf"
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-svc
spec:
  selector:
    app: redis-slave
  type: NodePort
  ports:
  - name: redis-slave
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 32380