apiVersion: rocketmq.apache.org/v1alpha1
kind: Console
metadata:
  name: console
  namespace: default
spec:
  # nameServers is the [ip:port] list of name service
  nameServers: ""
  # consoleDeployment define the console deployment
  consoleDeployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rocketmq-console
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rocketmq-console
      template:
        metadata:
          labels:
            app: rocketmq-console
        spec:
          containers:
            - name: console
              image: apacherocketmq/rocketmq-console:2.0.0
              type: NodePort
              ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-svc
spec:
  selector:
    app: redis-slave
  type: NodePort
  ports:
  - name: redis-slave
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 32380