apiVersion: v1
kind: Pod
metadata:
  name: simple-pvc
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports:
        - containerPort: 80
      volumeMounts:
        - name:  ng-logs
          mountPath:  /var/log/nginx
    - name: busybox
      image: busybox:1.30
      command:  ["/bin/sh", "-c", "tail -f /logs/access.log"]
      volumeMounts:
        - name: ng-logs
          mountPath: /logs
  volumes:
    - name: ng-logs
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false