apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  replicas: 1
  template:
    metadata:
      labels:
        app: es
    spec:
      restartPolicy: Always
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          command:
            - /bin/bash
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/{data,plugins};/bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
            - name: network.host
              value: 0.0.0.0
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: 1024Mi
              cpu: 50m
            limits:
              memory: 1024Mi
              cpu: 300m
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data 
            - mountPath: /usr/share/elasticsearch/plugins
              name: plugins
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: es-data-pvc
        - name: plugins
          persistentVolumeClaim:
            claimName: es-plugins-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  type: NodePort
  ports:
    - name: es
      port: 9200
  selector:
    app: es