apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /es/data
    server: 192.68.31.220

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-plugins
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /es/plugins
    server: 192.68.31.220